// PM2 Ecosystem Configuration for Discord Bots
// Copy to ecosystem.config.js and adjust DEPLOY_ROOT if needed.
// Set DEPLOY_ROOT env var or change default below (e.g. /root/discord-bots).

const ROOT = process.env.DEPLOY_ROOT || '/root/discord-bots';

module.exports = {
  apps: [
    {
      name: 'coding-practice-bot',
      script: 'index.js',
      cwd: `${ROOT}/coding-practice-bot`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: `${ROOT}/coding-practice-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/coding-practice-bot-error.log`,
      out_file: `${ROOT}/logs/coding-practice-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'subscription-tracker',
      script: 'index.js',
      cwd: `${ROOT}/subscription-tracker`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/subscription-tracker/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/subscription-tracker-error.log`,
      out_file: `${ROOT}/logs/subscription-tracker-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'grammar-bot',
      script: 'index.js',
      cwd: `${ROOT}/grammar-bot`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: `${ROOT}/grammar-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/grammar-bot-error.log`,
      out_file: `${ROOT}/logs/grammar-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'todoist-bot',
      script: 'index.js',
      cwd: `${ROOT}/todoist bot`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/todoist bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/todoist-bot-error.log`,
      out_file: `${ROOT}/logs/todoist-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'reddit-filter-bot',
      script: 'index.js',
      cwd: `${ROOT}/reddit-filter-bot`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/reddit-filter-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/reddit-filter-bot-error.log`,
      out_file: `${ROOT}/logs/reddit-filter-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'youtube-monitor-bot',
      script: 'index.js',
      cwd: `${ROOT}/youtube-monitor-bot`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/youtube-monitor-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/youtube-monitor-bot-error.log`,
      out_file: `${ROOT}/logs/youtube-monitor-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'github-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: `${ROOT}/github-bot`,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/github-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/github-bot-error.log`,
      out_file: `${ROOT}/logs/github-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'reminder-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: `${ROOT}/reminder-bot`,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/reminder-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/reminder-bot-error.log`,
      out_file: `${ROOT}/logs/reminder-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'starboard-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: `${ROOT}/starboard-bot`,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/starboard-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/starboard-bot-error.log`,
      out_file: `${ROOT}/logs/starboard-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'exercism-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: `${ROOT}/exercism-bot`,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: `${ROOT}/exercism-bot/.env`,
      env: {
        NODE_ENV: 'production',
      },
      error_file: `${ROOT}/logs/exercism-bot-error.log`,
      out_file: `${ROOT}/logs/exercism-bot-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-monolith',
      script: 'dist/main.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/backend-api`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        BACKEND_API_NODE_ENV: 'local',
        BACKEND_API_PORT: '8000',
        BACKEND_API_DEFAULT_MAX_FEEDS: '999999',
        BACKEND_API_DEFAULT_REFRESH_RATE_MINUTES: '60',
        BACKEND_API_USER_FEEDS_API_HOST: 'http://localhost:5000',
        BACKEND_API_FEED_REQUESTS_API_HOST: 'http://localhost:5000',
        BACKEND_API_FEED_USER_AGENT: 'MonitoRSS',
        BACKEND_API_RABBITMQ_BROKER_URL: 'amqp://guest:guest@localhost:5672/',
        BACKEND_API_USER_FEEDS_API_KEY: 'user-feeds-api-key',
        BACKEND_API_FEED_REQUESTS_API_KEY: 'feed-requests-api-key',
        LOG_LEVEL: 'info',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-monolith-error.log`,
      out_file: `${ROOT}/logs/monitorss-monolith-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-bot-presence',
      script: 'dist/main.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/bot-presence`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      env: {
        NODE_ENV: 'production',
        BOT_PRESENCE_RABBITMQ_URL: 'amqp://guest:guest@localhost:5672',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-bot-presence-error.log`,
      out_file: `${ROOT}/logs/monitorss-bot-presence-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-discord-rest-listener',
      script: 'build/app.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/discord-rest-listener`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        DISCORD_REST_LISTENER_RABBITMQ_URI: 'amqp://guest:guest@localhost:5672',
        DISCORD_REST_LISTENER_MAX_REQ_PER_SEC: '40',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-discord-rest-listener-error.log`,
      out_file: `${ROOT}/logs/monitorss-discord-rest-listener-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-feed-requests',
      script: 'dist/main.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/feed-requests`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      env: {
        NODE_ENV: 'local',
        FEED_REQUESTS_NODE_ENV: 'local',
        FEED_REQUESTS_POSTGRES_URI: 'postgres://postgres:postgres@localhost:5432/feedrequests',
        FEED_REQUESTS_POSTGRES_SCHEMA: 'feedrequests',
        FEED_REQUESTS_API_KEY: 'feed-requests-api-key',
        FEED_REQUESTS_API_PORT: '5001',
        FEED_REQUESTS_FEED_REQUEST_DEFAULT_USER_AGENT: 'MonitoRSS',
        FEED_REQUESTS_REDIS_URI: 'redis://localhost:6379',
        FEED_REQUESTS_REDIS_DISABLE_CLUSTER: 'true',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-feed-requests-error.log`,
      out_file: `${ROOT}/logs/monitorss-feed-requests-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-user-feeds',
      script: 'dist/index.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/user-feeds-next`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '640M',
      env: {
        NODE_ENV: 'production',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-user-feeds-error.log`,
      out_file: `${ROOT}/logs/monitorss-user-feeds-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-schedule-emitter',
      script: 'dist/scripts/schedule-emitter.js',
      cwd: `${ROOT}/news-bots/MonitoRSS/services/backend-api`,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        BACKEND_API_DEFAULT_MAX_FEEDS: '999999',
        BACKEND_API_DEFAULT_REFRESH_RATE_MINUTES: '60',
        BACKEND_API_FEED_USER_AGENT: 'MonitoRSS',
        BACKEND_API_USER_FEEDS_API_HOST: 'http://localhost:5000',
        BACKEND_API_FEED_REQUESTS_API_HOST: 'http://localhost:5000',
        BACKEND_API_USER_FEEDS_API_KEY: 'user-feeds-api-key',
        BACKEND_API_FEED_REQUESTS_API_KEY: 'feed-requests-api-key',
        BACKEND_API_RABBITMQ_BROKER_URL: 'amqp://guest:guest@localhost:5672/',
        DOTENV_CONFIG_PATH: `${ROOT}/news-bots/MonitoRSS/.env`,
      },
      error_file: `${ROOT}/logs/monitorss-schedule-emitter-error.log`,
      out_file: `${ROOT}/logs/monitorss-schedule-emitter-out.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
