// PM2 Ecosystem Configuration for Discord Bots
// Manages all bots with auto-restart, logging, and monitoring

module.exports = {
  apps: [
    {
      name: 'coding-practice-bot',
      script: './coding-practice-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/coding-practice-bot-error.log',
      out_file: './logs/coding-practice-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'command-control-bot',
      script: './command-control-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/command-control-bot-error.log',
      out_file: './logs/command-control-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'hangman-bot',
      script: './hangman-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/hangman-bot-error.log',
      out_file: './logs/hangman-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'spelling-bee-bot',
      script: './spelling-bee-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/spelling-bee-bot-error.log',
      out_file: './logs/spelling-bee-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'grammar-bot',
      script: './grammar-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/grammar-bot-error.log',
      out_file: './logs/grammar-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'todoist-bot',
      script: './todoist bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/todoist-bot-error.log',
      out_file: './logs/todoist-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'reddit-filter-bot',
      script: './reddit-filter-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/reddit-filter-bot-error.log',
      out_file: './logs/reddit-filter-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'youtube-monitor-bot',
      script: './youtube-monitor-bot/index.js',
      cwd: '/root/discord-bots',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/youtube-monitor-bot-error.log',
      out_file: './logs/youtube-monitor-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
