// PM2 Ecosystem Configuration for Discord Bots
// Manages all bots with auto-restart, logging, and monitoring

module.exports = {
  apps: [
    {
      name: 'coding-practice-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/coding-practice-bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: '/root/discord-bots/coding-practice-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/coding-practice-bot-error.log',
      out_file: '/root/discord-bots/logs/coding-practice-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'command-control-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/command-control-bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: '/root/discord-bots/command-control-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/command-control-bot-error.log',
      out_file: '/root/discord-bots/logs/command-control-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    // hangman-bot removed - archived on 2026-01-23 (friends not interested anymore)
    // spelling-bee-bot removed - directory exists but no index.js file found
    {
      name: 'grammar-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/grammar-bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env_file: '/root/discord-bots/grammar-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/grammar-bot-error.log',
      out_file: '/root/discord-bots/logs/grammar-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'todoist-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/todoist bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/todoist bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/todoist-bot-error.log',
      out_file: '/root/discord-bots/logs/todoist-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'reddit-filter-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/reddit-filter-bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/reddit-filter-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/reddit-filter-bot-error.log',
      out_file: '/root/discord-bots/logs/reddit-filter-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'youtube-monitor-bot',
      script: 'index.js',
      cwd: '/root/discord-bots/youtube-monitor-bot',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/youtube-monitor-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/youtube-monitor-bot-error.log',
      out_file: '/root/discord-bots/logs/youtube-monitor-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'github-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: '/root/discord-bots/github-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/github-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/github-bot-error.log',
      out_file: '/root/discord-bots/logs/github-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'reminder-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: '/root/discord-bots/reminder-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/reminder-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/reminder-bot-error.log',
      out_file: '/root/discord-bots/logs/reminder-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'starboard-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: '/root/discord-bots/starboard-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/starboard-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/starboard-bot-error.log',
      out_file: '/root/discord-bots/logs/starboard-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'exercism-bot',
      script: 'bot.py',
      interpreter: 'python3',
      cwd: '/root/discord-bots/exercism-bot',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env_file: '/root/discord-bots/exercism-bot/.env',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/root/discord-bots/logs/exercism-bot-error.log',
      out_file: '/root/discord-bots/logs/exercism-bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    // MonitoRSS Services
    // Note: .env file must be in /root/discord-bots/news-bots/MonitoRSS/.env
    // Services use dotenv to load it automatically
    {
      name: 'monitorss-monolith',
      script: 'dist/main.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/backend-api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        BACKEND_API_NODE_ENV: 'local',
        BACKEND_API_PORT: '8000',
        BACKEND_API_DEFAULT_MAX_FEEDS: '999999',
        BACKEND_API_DEFAULT_REFRESH_RATE_MINUTES: '60',
        BACKEND_API_USER_FEEDS_API_HOST: 'http://localhost:5000',
        BACKEND_API_FEED_REQUESTS_API_HOST: 'http://localhost:5000',
        BACKEND_API_FEED_USER_AGENT: 'MonitoRSS',
        BACKEND_API_RABBITMQ_BROKER_URL: 'amqp://guest:guest@localhost:5672/',
        BACKEND_API_USER_FEEDS_API_KEY: 'user-feeds-api-key',
        BACKEND_API_FEED_REQUESTS_API_KEY: 'feed-requests-api-key',
        LOG_LEVEL: 'info',
        // All sensitive values loaded from .env file via DOTENV_CONFIG_PATH
        // DO NOT hardcode tokens, secrets, or database URIs here
        // Point NestJS ConfigModule to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-monolith-error.log',
      out_file: '/root/discord-bots/logs/monitorss-monolith-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-bot-presence',
      script: 'dist/main.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/bot-presence',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      env: {
        NODE_ENV: 'production',
        BOT_PRESENCE_RABBITMQ_URL: 'amqp://guest:guest@localhost:5672',
        // Point NestJS ConfigModule to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-bot-presence-error.log',
      out_file: '/root/discord-bots/logs/monitorss-bot-presence-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-discord-rest-listener',
      script: 'build/app.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/discord-rest-listener',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        DISCORD_REST_LISTENER_RABBITMQ_URI: 'amqp://guest:guest@localhost:5672',
        DISCORD_REST_LISTENER_MAX_REQ_PER_SEC: '40',
        // Point dotenv to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-discord-rest-listener-error.log',
      out_file: '/root/discord-bots/logs/monitorss-discord-rest-listener-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-feed-requests',
      script: 'dist/main.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/feed-requests',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      env: {
        NODE_ENV: 'local',
        FEED_REQUESTS_NODE_ENV: 'local',
        FEED_REQUESTS_POSTGRES_URI: 'postgres://postgres:postgres@localhost:5432/feedrequests',
        FEED_REQUESTS_POSTGRES_SCHEMA: 'feedrequests',
        FEED_REQUESTS_API_KEY: 'feed-requests-api-key',
        FEED_REQUESTS_API_PORT: '5001',
        FEED_REQUESTS_FEED_REQUEST_DEFAULT_USER_AGENT: 'MonitoRSS',
        FEED_REQUESTS_REDIS_URI: 'redis://localhost:6379',
        FEED_REQUESTS_REDIS_DISABLE_CLUSTER: 'true',
        // Point dotenv to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-feed-requests-error.log',
      out_file: '/root/discord-bots/logs/monitorss-feed-requests-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-user-feeds',
      script: 'dist/index.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/user-feeds-next',
      instances: 1,
      exec_mode: 'fork', // Use fork mode instead of cluster for Fastify compatibility
      autorestart: true,
      watch: false,
      max_memory_restart: '640M',
      env: {
        NODE_ENV: 'production',
        // Point dotenv to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-user-feeds-error.log',
      out_file: '/root/discord-bots/logs/monitorss-user-feeds-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'monitorss-schedule-emitter',
      script: 'dist/scripts/schedule-emitter.js',
      cwd: '/root/discord-bots/news-bots/MonitoRSS/services/backend-api',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        // All sensitive values loaded from .env file via DOTENV_CONFIG_PATH
        // DO NOT hardcode tokens, secrets, database URIs, or API keys here
        // Point NestJS ConfigModule to parent .env file
        DOTENV_CONFIG_PATH: '/root/discord-bots/news-bots/MonitoRSS/.env',
      },
      error_file: '/root/discord-bots/logs/monitorss-schedule-emitter-error.log',
      out_file: '/root/discord-bots/logs/monitorss-schedule-emitter-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};
